openapi: 3.0.0
info:
  title: Contact Management API
  description: API for managing contacts using Express.js and Mongoose
  version: 1.0.0
paths:
  /adddata:
    post:
      summary: Add a new contact
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                contact:
                  type: string
      responses:
        "200":
          description: Successfully added contact
        "400":
          description: Invalid request body
  /showdata:
    get:
      summary: Retrieve all contacts
      responses:
        "200":
          description: A list of contacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        contact:
                          type: string
        "404":
          description: No contacts found
  /showdata/{name}:
    get:
      summary: Retrieve contact by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Found contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  contact:
                    type: string
        "404":
          description: Contact not found
  /showdatacon/{contact}:
    get:
      summary: Retrieve contact by contact number
      parameters:
        - name: contact
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Found contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  contact:
                    type: string
        "404":
          description: Contact not found
  /updatedata/{name}:
    put:
      summary: Update contact by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                contact:
                  type: string
      responses:
        "200":
          description: Updated contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  contact:
                    type: string
        "404":
          description: Contact not found
  /updatedatabycon/{contact}:
    put:
      summary: Update contact by contact number
      parameters:
        - name: contact
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Updated contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  contact:
                    type: string
        "404":
          description: Contact not found
  /deletedata/{name}:
    delete:
      summary: Delete contact by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contact deleted
        "404":
          description: Contact not found
